In [6]:
!pip3 install pyspark
!pip3 install findspark

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting pyspark
  Using cached pyspark-3.3.0.tar.gz (281.3 MB)
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.5
  Using cached py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.0-py2.py3-none-any.whl size=281764027 sha256=442049519e5dcf30c43e4936c5069fcbd4ae3ebee5469ff8fc7681a3057b3d88
  Stored in directory: /Users/thomaslaurel/Library/Caches/pip/wheels/1d/27/68/1382001655ef41217e1dd34d59aa777612135379bab64279e9
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.5 pyspark-3.3.0

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting findspark
  Using cached findspark-2.0.1-py2.py3-none-any.whl (4.4 kB)
Installing collected packages: findspark
Successfully installed findspark-2.0.1

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [11]:
!pip3 install matplotlib

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting matplotlib
  Downloading matplotlib-3.6.1-cp38-cp38-macosx_10_12_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 9.6 MB/s eta 0:00:00:00:0100:01
Requirement already satisfied: python-dateutil>=2.7 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib) (2.8.2)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.5-cp38-cp38-macosx_10_9_x86_64.whl (241 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.2/241.2 kB 8.9 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.37.4-py3-none-any.whl (960 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 960.8/960.8 kB 4.8 MB/s eta 0:00:0000:0100:01
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp38-cp38-macosx_10_9_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 657.6 kB/s eta 0:00:00a 0:00:01
Requirement already satisfied: pyparsing>=2.2.1 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: numpy>=1.19 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib) (1.23.4)
Collecting pillow>=6.2.0
  Downloading Pillow-9.2.0-cp38-cp38-macosx_10_10_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 7.4 MB/s eta 0:00:0000:0100:01m
Requirement already satisfied: packaging>=20.0 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib) (21.3)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib) (1.15.0)
Installing collected packages: pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/Users/thomaslaurel/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed contourpy-1.0.5 cycler-0.11.0 fonttools-4.37.4 kiwisolver-1.4.4 matplotlib-3.6.1 pillow-9.2.0

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [13]:
!pip3 install seaborn

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Collecting seaborn
  Downloading seaborn-0.12.1-py3-none-any.whl (288 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 3.8 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: pandas>=0.25 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from seaborn) (1.5.0)
Collecting matplotlib!=3.6.1,>=3.1
  Downloading matplotlib-3.6.0-cp38-cp38-macosx_10_12_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 5.2 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: numpy>=1.17 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from seaborn) (1.23.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.0.5)
Requirement already satisfied: python-dateutil>=2.7 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.37.4)
Requirement already satisfied: pytz>=2020.1 in /Users/thomaslaurel/Library/Python/3.8/lib/python/site-packages (from pandas>=0.25->seaborn) (2022.4)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.15.0)
Installing collected packages: matplotlib, seaborn
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.6.1
    Uninstalling matplotlib-3.6.1:
      Successfully uninstalled matplotlib-3.6.1
Successfully installed matplotlib-3.6.0 seaborn-0.12.1

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: /Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip

In [7]:
import pyspark

In [14]:
import findspark
import json
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [15]:
df = pd.read_csv("/Users/thomaslaurel/Desktop/jump/ETLProject/ETL-Project-1/Spotify-2000.csv")

In [17]:
df.head()

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59

In [21]:
df_1 = df[["Index","Artist","Title","Top Genre","Year","Danceability","Popularity","Energy","Length (Duration)","Beats Per Minute (BPM)"]]
df_1

,Index,Artist,Title,Top Genre,Year,Danceability,Popularity,Energy,Length (Duration),Beats Per Minute (BPM)
0,1,Norah Jones,Sunrise,adult standards,2004,53,71,30,201,157
1,2,Deep Purple,Black Night,album rock,2000,50,39,79,207,135
2,3,Gorillaz,Clint Eastwood,alternative hip hop,2001,66,69,69,341,168
3,4,Foo Fighters,The Pretender,alternative metal,2007,43,76,96,269,173
4,5,Bruce Springsteen,Waitin' On A Sunny Day,classic rock,2002,58,59,82,256,106
...,...,...,...,...,...,...,...,...,...,...
1989,1990,Elvis Presley,Heartbreak Hotel,adult standards,1958,70,63,21,128,94
1990,1991,Elvis Presley,Hound Dog,adult standards,1958,36,69,76,136,175
1991,1992,Chuck Berry,Johnny B. Goode,blues rock,1959,53,74,80,162,168
1992,1993,The Dave Brubeck Quartet,Take Five,bebop,1959,45,65,26,324,174
1993,1994,Fats Domino,Blueberry Hill,adult standards,1959,49,56,50,148,133

In [146]:
#have to get the unique song and artist pair to find the genre to include the genre ID.
df_1[df_1["Artist"] == "Norah Jones"]["Top Genre"]
# df_1[(df_1["Title"] ==  "Sunrise") & (df_1["Artist"] == "Norah Jones")]["Top Genre"]
#df_1["Title"][0]
#df_1[(df_1["Title"] ==  "Clint Eastwood")]

0     adult standards
33    adult standards
Name: Top Genre, dtype: object

In [22]:
df_2 = df[["Artist","Title"]]
df_2["Index"] =

In [27]:
df_1["Top Genre"].value_counts().count()

149

In [175]:
#creates the genre table with all the genres present in the original dataFrame, includes duplicates
df_3 = df[["Top Genre"]]
#removes the duplicates from df_3
df_3.drop_duplicates(inplace = True)
#assign each genre its own unique ID
df_3.insert(0, "Genre_ID", range(0, 149))

/var/folders/yt/ff8t9qs52f7d88_lbx_lkk2m0000gn/T/ipykernel_10590/2022681586.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3.drop_duplicates(inplace = True)

In [176]:
#df_3.set_index("Genre_ID", inplace = True)
df_3

      Genre_ID                Top Genre
0            0          adult standards
1            1               album rock
2            2      alternative hip hop
3            3        alternative metal
4            4             classic rock
...        ...                      ...
1761       144  german alternative rock
1817       145      classic italian pop
1820       146                 pop punk
1880       147                   motown
1992       148                    bebop

[149 rows x 2 columns]

In [201]:
(df_3[df_3["Top Genre"] == "adult standards"])["Genre_ID"]

0    0
Name: Genre_ID, dtype: int64

In [204]:
# SONG > Genre > Genre is in genre table
#Song File Table
#Index, Artist Name(FK), Song Title, Year, Genre ID(FK)
df_4 = df[["Index", "Artist", "Title", "Year"]] #add genre id col from df_3

In [123]:
df_4

      Index                    Artist                   Title  Year
0         1               Norah Jones                 Sunrise  2004
1         2               Deep Purple             Black Night  2000
2         3                  Gorillaz          Clint Eastwood  2001
3         4              Foo Fighters           The Pretender  2007
4         5         Bruce Springsteen  Waitin' On A Sunny Day  2002
...     ...                       ...                     ...   ...
1989   1990             Elvis Presley        Heartbreak Hotel  1958
1990   1991             Elvis Presley               Hound Dog  1958
1991   1992               Chuck Berry         Johnny B. Goode  1959
1992   1993  The Dave Brubeck Quartet               Take Five  1959
1993   1994               Fats Domino          Blueberry Hill  1959

[1994 rows x 4 columns]

In [205]:
#df_1[(df_1["Title"] ==  "Sunrise") & (df_1["Artist"] == "Norah Jones")]["Top Genre"]
#df_3[df_3["Top Genre"] == "adult standards"]["Genre_ID"]
df_4.assign(Genre = lambda x: (df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])]["Top Genre"]))
#df_4.assign(Genre_ID = lambda x: (df_3[df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])]["Top Genre"]]["Genre_ID"]))

,Index,Artist,Title,Year,Genre
0,1,Norah Jones,Sunrise,2004,adult standards
1,2,Deep Purple,Black Night,2000,album rock
2,3,Gorillaz,Clint Eastwood,2001,alternative hip hop
3,4,Foo Fighters,The Pretender,2007,alternative metal
4,5,Bruce Springsteen,Waitin' On A Sunny Day,2002,classic rock
...,...,...,...,...,...
1989,1990,Elvis Presley,Heartbreak Hotel,1958,adult standards
1990,1991,Elvis Presley,Hound Dog,1958,adult standards
1991,1992,Chuck Berry,Johnny B. Goode,1959,blues rock
1992,1993,The Dave Brubeck Quartet,Take Five,1959,bebop
1993,1994,Fats Domino,Blueberry Hill,1959,adult standards

In [207]:
# this df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])]["Top Genre"]) returns the TOP GENRE
#(df_3[df_3["Top Genre"]] == (df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])]["Top Genre"])["Genre_ID"])
#df_4.assign(Genre_ID = lambda x: (df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])]["Top Genre"]))
#df_3[df_3["Top Genre"] == "adult standards"]
#df_4.assign(Genre_ID = lambda x: ((df_3[df_3["Top Genre"] == (df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])])]["Top Genre"])["Genre_ID"]))
#(df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])]["Top Genre"])
df_4.assign(Genre_ID = lambda x: ((df_3[df_3["Top Genre"] == (df_1[(df_1["Title"] == x["Title"]) & (df_1["Artist"] == x["Artist"])]["Top Genre"])])["Genre_ID"]))

ValueError: Can only compare identically-labeled Series objects

In [157]:
df_dummy

,Index,Artist,Title,Year,Top Genre
0,1,Norah Jones,Sunrise,2004,adult standards
1,2,Deep Purple,Black Night,2000,album rock
2,3,Gorillaz,Clint Eastwood,2001,alternative hip hop
3,4,Foo Fighters,The Pretender,2007,alternative metal
4,5,Bruce Springsteen,Waitin' On A Sunny Day,2002,classic rock
...,...,...,...,...,...
1989,1990,Elvis Presley,Heartbreak Hotel,1958,adult standards
1990,1991,Elvis Presley,Hound Dog,1958,adult standards
1991,1992,Chuck Berry,Johnny B. Goode,1959,blues rock
1992,1993,The Dave Brubeck Quartet,Take Five,1959,bebop
1993,1994,Fats Domino,Blueberry Hill,1959,adult standards